### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/stock-logistics-barcode#109]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] barcode_link
- [ ] barcodes_ean14
- [x] barcodes_generator_abstract - By @phatnguyenuit - ~~#122~~ #138 
- [ ] barcodes_generator_location - By @misern2 - #137 
- [x] barcodes_generator_lot - By @misern2 - #139 
- [ ] barcodes_generator_package - By @misern2 - #141 
- [x] barcodes_generator_partner - By @xavierjimenez - #142 
- [x] barcodes_generator_picking - By @xavierjimenez - #143 
- [x] barcodes_generator_product - By @phatnguyenuit - #124 
- [ ] base_gs1_barcode
- [ ] mobile_app_inventory - By @abondis - #176
- [x] product_multi_ean - By @xavierjimenez  - #140 
- [x] stock_scanner - #110 
- [x] stock_scanner_inventory By @misern2  - #150 
- [x] stock_scanner_location_info By @misern2 - #151 
- [x] stock_scanner_receipt By @misern2 - #154

**Comment by Garamotte** [comment]
Migration of `stock_scanner`: https://github.com/OCA/stock-logistics-barcode/pull/110

**Comment by emagdalenaC2i** [comment]
@pedrobaeza stock_scanner #110 is done

**Comment by pedrobaeza** [comment]
Right, noted
