### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/stock-logistics-barcode#20]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] base_gs1_barcode
- [ ] tr_barcode_on_tracking
- [ ] tr_barcode_on_product
- [x] ~~product_barcode_generator~~ - Removed as obsolete - Replaced by _barcodes_generator_product_
- [ ] tr_barcode_on_prodlots
- [ ] tr_barcode_on_picking
- [ ] tr_barcode_field
- [ ] tr_barcode_config
- [ ] barcode_link
- [ ] tr_barcode
- [ ] product_multi_ean
