### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/stock-logistics-barcode#45]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] barcode_link
- [ ] base_gs1_barcode
- [x] ~~product_barcode_generator - By @JosDeGraeve - #63~~ Deprecated
- [ ] barcodes_generator_abstract - #65
- [ ] barcodes_generator_product - #66
- [ ] barcodes_generator_partner - #67 
- [ ] mobile_app_inventory - By @abondis - #174 
- [ ] product_multi_ean
- [ ] stock_inventory_barcode - By @gurneyalex - #129 
- [x] stock_scanner - By @sylvain-garancher - #46
- [x] stock_scanner_receipt By @misern2 - #146 
- [x] ~~tr_barcode~~ Removed as obsolete
- [x] ~~tr_barcode_config~~ Removed as obsolete
- [x] ~~tr_barcode_field~~ Removed as obsolete
- [x] ~~tr_barcode_on_picking~~ Removed as obsolete
- [x] ~~tr_barcode_on_prodlots~~ Removed as obsolete
- [x] ~~tr_barcode_on_product~~ Removed as obsolete
- [x] ~~tr_barcode_on_tracking~~ Removed as obsolete

**Comment by Garamotte** [comment]
Migration of the stock_scanner module here : https://github.com/OCA/stock-logistics-barcode/pull/46

**Comment by JosDeGraeve** [comment]
Migration of the product_barcode_generator here: #63

**Comment by lasley** [comment]
Added the `barcodes_generator_*` modules and claimed `_abstract`, which I should be submitting in the next few hours.
